# pyproject.toml
[project]
name = "git-summarize"
version = "0.2.0"
description = "Generate commit messages using LLM"
dependencies = [
    "openai>=1.0.0",
    "typer>=0.6.1",
    "requests",
    "rich>=13.0.0",
]

[project.scripts]
git-summarize = "git_summarize.cli:app"
